"""
Type-safe config classes re-exported from ``interactly-configs``.

Available when the SDK is installed with the ``configs`` extra::

    pip install "interactly[configs]"

Usage::

    from interactly.configs import (
        WorkflowConfig,
        BaseNodeConfig,
        EdgeConfig,
        DirectEdgeConfig,
        ConditionalEdgeConfig,
        ToolConfig,
        LLMConfig,
        PromptConfig,
    )

All exported names are the same as those in ``interactly_configs`` — this
module is a convenience facade so callers need only one SDK import path. The
list below is kept exhaustive by ``tests/unit/test_configs_module.py``, which
fails if the two ``__all__`` sets diverge: a facade that silently omits a new
symbol is worse than no facade, because the omission looks like the symbol not
existing.

If ``interactly-configs`` is not installed, importing this module raises an
``ImportError`` with installation instructions.
"""

from __future__ import annotations

try:
    from interactly_configs import (
        ADAPTIVE_THINKING_MODELS,
        ALWAYS_THINKING_ANTHROPIC_MODELS,
        ALWAYS_THINKING_GOOGLE_MODELS,
        COMPANION_THREAD_DELIMITER,
        DEFAULT_ADAPTIVE_THINKING_MAX_TOKENS,
        DEFAULT_MAX_TOKENS,
        LOW_REASONING_EFFORTS,
        MAX_COMMENT_LENGTH,
        MINIMUM_PRO_REASONING_EFFORT,
        MODELS_WITHOUT_LOW_REASONING_EFFORT,
        RATING_SCORES,
        AnthropicLLMConfig,
        ANTHROPICModel,
        APIMethodType,
        AzureOpenAILLMConfig,
        AZUREOPENAIModel,
        BaseEdgeConfig,
        BaseEdgeRunInput,
        BaseEntityConfig,
        BaseLLMConfig,
        BaseLLMNodeConfig,
        BaseNodeConfig,
        BaseNodeRunInput,
        BaseNodeRunOutput,
        BaseRunInput,
        BaseRunOutput,
        BaseToolConfig,
        BedrockLLMConfig,
        BEDROCKModel,
        BodyContentTypeEnum,
        CommentConfig,
        CommentRequest,
        CompanionEdgeConfig,
        CompanionThreadConfig,
        ConditionalEdgeConfig,
        ConditionConfig,
        CustomLLMConfig,
        DeduplicateNodeConfig,
        DirectEdgeConfig,
        DynamicMessagesConfig,
        EdgeConfig,
        EdgeType,
        EndConversationNodeConfig,
        EvaluateWhileWaitingConfig,
        EvaluationConfig,
        EvaluationRunInfo,
        ExternalAPIToolConfig,
        FieldExtractorNodeConfig,
        GlobalConditionEdgeEvaluationMethod,
        GlobalNodeConfig,
        GoogleLLMConfig,
        GOOGLEModel,
        HttpMethodEnum,
        HttpRequestNodeConfig,
        InbuiltFunctionToolConfig,
        InlinePythonToolConfig,
        IntegrationAuthConfig,
        KnowledgeBaseToolConfig,
        LLMConfig,
        LLMConfigUnion,
        LLMGroupConfig,
        LLMGroupWithBackchannelConfig,
        LLMLatencyStats,
        LLMLatencyStatsByModel,
        LLMNodeRunInput,
        LLMOrGroupConfig,
        LLMProvider,
        LLMTokenUsage,
        LLMTokenUsageByModel,
        MCPServerConfig,
        NodeCategory,
        NodeConfig,
        NodeLibraryConfig,
        NodeRunInput,
        NodeRunOutput,
        NodesRunInputs,
        NodeType,
        NoLLMConfig,
        NoOpNodeConfig,
        NoOpNodeRunInput,
        NoOpNodeRunOutput,
        OktaAuthConfig,
        OpenAILLMConfig,
        OPENAIModel,
        OperationMode,
        PromptConfig,
        RatingConfig,
        RatingRequest,
        RatingValue,
        ResponseFormatEnum,
        SayLLMNodeConfig,
        SayLLMNodeRunOutput,
        SayStaticMessageNodeConfig,
        SelectionMode,
        SelfLoopConfig,
        SendSMSNodeConfig,
        StartConversationNodeConfig,
        StaticMessagesConfig,
        SuperNodeConfig,
        SuperNodeFieldMapping,
        SuperNodeFieldMappingTargetType,
        SuperNodeInputField,
        SuperNodeInputFieldValueType,
        SuperNodeInterface,
        ToolConfig,
        ToolNodeConfig,
        ToolsConfig,
        ToolType,
        WaitingEvaluationTriggerMode,
        WorkerLLMNodeConfig,
        WorkerLLMNodeRunOutput,
        WorkflowCommand,
        WorkflowConfig,
        WorkflowConfigFullyHydrated,
        WorkflowDefaultLLMConfig,
        WorkflowExecutionStatus,
        WorkflowRun,
        WorkflowRunEvalLLMNodeConfig,
        WorkflowRunFetchNodeConfig,
        WorkflowRunInput,
        WorkflowRunInputOutputPair,
        WorkflowRunOutput,
        WorkflowStatus,
        WorkflowTemplateConfig,
        edge_companion_thread_id,
        edge_evaluates_while_waiting,
        edge_is_companion,
        edge_waiting_evaluation_config,
        get_node_config_class,
        resolve_reasoning_effort,
    )
except ImportError as _err:  # pragma: no cover
    raise ImportError(
        "interactly-configs is not installed.\n"
        "Install it with:\n\n"
        "    pip install \"interactly[configs]\"\n"
    ) from _err

__all__ = [
    "ADAPTIVE_THINKING_MODELS",
    "ALWAYS_THINKING_ANTHROPIC_MODELS",
    "ALWAYS_THINKING_GOOGLE_MODELS",
    "ANTHROPICModel",
    "APIMethodType",
    "AZUREOPENAIModel",
    "AnthropicLLMConfig",
    "AzureOpenAILLMConfig",
    "BEDROCKModel",
    "BaseEdgeConfig",
    "BaseEdgeRunInput",
    "BaseEntityConfig",
    "BaseLLMConfig",
    "BaseLLMNodeConfig",
    "BaseNodeConfig",
    "BaseNodeRunInput",
    "BaseNodeRunOutput",
    "BaseRunInput",
    "BaseRunOutput",
    "BaseToolConfig",
    "BedrockLLMConfig",
    "BodyContentTypeEnum",
    "COMPANION_THREAD_DELIMITER",
    "CommentConfig",
    "CommentRequest",
    "CompanionEdgeConfig",
    "CompanionThreadConfig",
    "ConditionConfig",
    "ConditionalEdgeConfig",
    "CustomLLMConfig",
    "DEFAULT_ADAPTIVE_THINKING_MAX_TOKENS",
    "DEFAULT_MAX_TOKENS",
    "DeduplicateNodeConfig",
    "DirectEdgeConfig",
    "DynamicMessagesConfig",
    "EdgeConfig",
    "EdgeType",
    "EndConversationNodeConfig",
    "EvaluateWhileWaitingConfig",
    "EvaluationConfig",
    "EvaluationRunInfo",
    "ExternalAPIToolConfig",
    "FieldExtractorNodeConfig",
    "GOOGLEModel",
    "GlobalConditionEdgeEvaluationMethod",
    "GlobalNodeConfig",
    "GoogleLLMConfig",
    "HttpMethodEnum",
    "HttpRequestNodeConfig",
    "InbuiltFunctionToolConfig",
    "InlinePythonToolConfig",
    "KnowledgeBaseToolConfig",
    "LLMConfig",
    "LLMConfigUnion",
    "LLMGroupConfig",
    "LLMGroupWithBackchannelConfig",
    "LLMLatencyStats",
    "LLMLatencyStatsByModel",
    "LLMNodeRunInput",
    "LLMOrGroupConfig",
    "LLMProvider",
    "LLMTokenUsage",
    "LLMTokenUsageByModel",
    "LOW_REASONING_EFFORTS",
    "MAX_COMMENT_LENGTH",
    "MCPServerConfig",
    "MINIMUM_PRO_REASONING_EFFORT",
    "MODELS_WITHOUT_LOW_REASONING_EFFORT",
    "NoLLMConfig",
    "NoOpNodeConfig",
    "NoOpNodeRunInput",
    "NoOpNodeRunOutput",
    "NodeCategory",
    "NodeConfig",
    "NodeLibraryConfig",
    "NodeRunInput",
    "NodeRunOutput",
    "NodeType",
    "NodesRunInputs",
    "OPENAIModel",
    "IntegrationAuthConfig",
    "OktaAuthConfig",
    "OpenAILLMConfig",
    "OperationMode",
    "PromptConfig",
    "RATING_SCORES",
    "RatingConfig",
    "RatingRequest",
    "RatingValue",
    "ResponseFormatEnum",
    "SayLLMNodeConfig",
    "SayLLMNodeRunOutput",
    "SayStaticMessageNodeConfig",
    "SelectionMode",
    "SelfLoopConfig",
    "SendSMSNodeConfig",
    "StartConversationNodeConfig",
    "StaticMessagesConfig",
    "SuperNodeConfig",
    "SuperNodeFieldMapping",
    "SuperNodeFieldMappingTargetType",
    "SuperNodeInputField",
    "SuperNodeInputFieldValueType",
    "SuperNodeInterface",
    "ToolConfig",
    "ToolNodeConfig",
    "ToolType",
    "ToolsConfig",
    "WaitingEvaluationTriggerMode",
    "WorkerLLMNodeConfig",
    "WorkerLLMNodeRunOutput",
    "WorkflowCommand",
    "WorkflowConfig",
    "WorkflowConfigFullyHydrated",
    "WorkflowDefaultLLMConfig",
    "WorkflowExecutionStatus",
    "WorkflowRun",
    "WorkflowRunEvalLLMNodeConfig",
    "WorkflowRunFetchNodeConfig",
    "WorkflowRunInput",
    "WorkflowRunInputOutputPair",
    "WorkflowRunOutput",
    "WorkflowStatus",
    "WorkflowTemplateConfig",
    "edge_companion_thread_id",
    "edge_evaluates_while_waiting",
    "edge_is_companion",
    "edge_waiting_evaluation_config",
    "get_node_config_class",
    "resolve_reasoning_effort",
]

#: ``interactly_configs.__version__`` is deliberately NOT re-exported. ``interactly.__version__`` is
#: the SDK's own version, and having a second, different one reachable from an ``interactly.*`` path
#: is a trap rather than a convenience.
