"""
Type-safe config classes re-exported from ``interactly-configs``.

Available when the SDK is installed with the ``configs`` extra::

    pip install "interactly[configs]"

Usage::

    from interactly.configs import (
        WorkflowConfig,
        BaseNodeConfig,
        EdgeConfig,
        DirectEdgeConfig,
        ConditionalEdgeConfig,
        ToolConfig,
        LLMConfig,
        PromptConfig,
    )

All exported names are the same as those in ``interactly_configs`` — this
module is a convenience facade so callers need only one SDK import path.

If ``interactly-configs`` is not installed, importing this module raises an
``ImportError`` with installation instructions.
"""

from __future__ import annotations

try:
    from interactly_configs import (  # type: ignore[import]
        AnthropicLLMConfig,
        ANTHROPICModel,
        AzureOpenAILLMConfig,
        AZUREOPENAIModel,
        BaseEdgeRunInput,
        BaseEntityConfig,
        BaseLLMConfig,
        BaseLLMNodeConfig,
        BaseNodeConfig,
        BaseNodeRunInput,
        BaseNodeRunOutput,
        BaseRunInput,
        BaseRunOutput,
        BaseToolConfig,
        BodyContentTypeEnum,
        CompanionEdgeConfig,
        ConditionalEdgeConfig,
        ConditionConfig,
        CustomLLMConfig,
        DirectEdgeConfig,
        DynamicMessagesConfig,
        EdgeConfig,
        EdgeType,
        EndConversationNodeConfig,
        ExternalAPIToolConfig,
        GlobalConditionEdgeEvaluationMethod,
        GlobalDefaultLLMConfig,
        GlobalNodeConfig,
        GoogleLLMConfig,
        GOOGLEModel,
        HttpMethodEnum,
        HttpRequestNodeConfig,
        InbuiltFunctionToolConfig,
        InlinePythonToolConfig,
        KnowledgeBaseToolConfig,
        LLMConfig,
        LLMConfigUnion,
        LLMGroupConfig,
        LLMGroupWithBackchannelConfig,
        LLMNodeRunInput,
        LLMOrGroupConfig,
        LLMProvider,
        MCPServerConfig,
        NodeCategory,
        NodeConfig,
        NodeLibraryConfig,
        NodeRunInput,
        NodeRunOutput,
        NodesRunInputs,
        NodeType,
        OktaAuthConfig,
        OpenAILLMConfig,
        OPENAIModel,
        OperationMode,
        PromptConfig,
        ResponseFormatEnum,
        SayLLMNodeConfig,
        SayLLMNodeRunOutput,
        SayStaticMessageNodeConfig,
        SelectionMode,
        SendSMSNodeConfig,
        StartConversationNodeConfig,
        StaticMessagesConfig,
        SuperNodeConfig,
        SuperNodeFieldMapping,
        SuperNodeFieldMappingTargetType,
        SuperNodeInputField,
        SuperNodeInputFieldValueType,
        SuperNodeInterface,
        ToolConfig,
        ToolNodeConfig,
        ToolsConfig,
        ToolType,
        WorkerLLMNodeConfig,
        WorkerLLMNodeRunOutput,
        WorkflowCommand,
        WorkflowConfig,
        WorkflowConfigFullyHydrated,
        WorkflowExecutionStatus,
        WorkflowRunEvalLLMNodeConfig,
        WorkflowRunFetchNodeConfig,
        WorkflowRunInput,
        WorkflowRunInputOutputPair,
        WorkflowRunOutput,
        WorkflowTemplateConfig,
    )
except ImportError as _err:  # pragma: no cover
    raise ImportError(
        "interactly-configs is not installed.\n"
        "Install it with:\n\n"
        "    pip install \"interactly[configs]\"\n"
    ) from _err

__all__ = [
    "ANTHROPICModel",
    "AZUREOPENAIModel",
    "AnthropicLLMConfig",
    "AzureOpenAILLMConfig",
    "BaseEdgeRunInput",
    "BaseEntityConfig",
    "BaseLLMConfig",
    "BaseLLMNodeConfig",
    "BaseNodeConfig",
    "BaseNodeRunInput",
    "BaseNodeRunOutput",
    "BaseRunInput",
    "BaseRunOutput",
    "BaseToolConfig",
    "BodyContentTypeEnum",
    "CompanionEdgeConfig",
    "ConditionConfig",
    "ConditionalEdgeConfig",
    "CustomLLMConfig",
    "DirectEdgeConfig",
    "DynamicMessagesConfig",
    "EdgeConfig",
    "EdgeType",
    "EndConversationNodeConfig",
    "ExternalAPIToolConfig",
    "GOOGLEModel",
    "GlobalConditionEdgeEvaluationMethod",
    "GlobalDefaultLLMConfig",
    "GlobalNodeConfig",
    "GoogleLLMConfig",
    "HttpMethodEnum",
    "HttpRequestNodeConfig",
    "InbuiltFunctionToolConfig",
    "InlinePythonToolConfig",
    "KnowledgeBaseToolConfig",
    "LLMConfig",
    "LLMConfigUnion",
    "LLMGroupConfig",
    "LLMGroupWithBackchannelConfig",
    "LLMNodeRunInput",
    "LLMOrGroupConfig",
    "LLMProvider",
    "MCPServerConfig",
    "NodeCategory",
    "NodeConfig",
    "NodeLibraryConfig",
    "NodeRunInput",
    "NodeRunOutput",
    "NodeType",
    "NodesRunInputs",
    "OPENAIModel",
    "OktaAuthConfig",
    "OpenAILLMConfig",
    "OperationMode",
    "PromptConfig",
    "ResponseFormatEnum",
    "SayLLMNodeConfig",
    "SayLLMNodeRunOutput",
    "SayStaticMessageNodeConfig",
    "SelectionMode",
    "SendSMSNodeConfig",
    "StartConversationNodeConfig",
    "StaticMessagesConfig",
    "SuperNodeConfig",
    "SuperNodeInterface",
    "SuperNodeInputField",
    "SuperNodeFieldMapping",
    "SuperNodeFieldMappingTargetType",
    "SuperNodeInputFieldValueType",
    "ToolConfig",
    "ToolNodeConfig",
    "ToolsConfig",
    "ToolType",
    "WorkerLLMNodeConfig",
    "WorkerLLMNodeRunOutput",
    "WorkflowCommand",
    "WorkflowConfig",
    "WorkflowConfigFullyHydrated",
    "WorkflowTemplateConfig",
    "WorkflowExecutionStatus",
    "WorkflowRunEvalLLMNodeConfig",
    "WorkflowRunFetchNodeConfig",
    "WorkflowRunInput",
    "WorkflowRunInputOutputPair",
    "WorkflowRunOutput",
]

try:
    # Availability probe, not a re-export: the name is published via __all__ below only when the
    # optional `interactly_configs` package exposes it. noqa because ruff sees an unused import.
    from interactly_configs import get_node_config_class  # noqa: F401

    __all__.append("get_node_config_class")
except ImportError:
    pass
